apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.deployment.image.repository }}:{{ .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: {{ .Values.deployment.portName }}
              containerPort: {{ .Values.deployment.port }}
              protocol: {{ .Values.deployment.protocol }}
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.HTTPpath }}
              port: {{ .Values.deployment.portName }}
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.HTTPpath }}
              port: {{ .Values.deployment.portName }}
  strategy:
    canary:
      canaryService: {{ .Release.Name }}-canary
      stableService: {{ .Release.Name }}-stable
      trafficRouting:
        istio:
          virtualServices:
          - name: {{ .Release.Name }}-vsvc
            routes:
            - primary
      steps:
      - setWeight: 10
      - pause: {} # pause indefinitely
      - setWeight: 20
      - pause: {duration: 20s}
      - setWeight: 30
      - pause: {duration: 20s}
      - setWeight: 40
      - pause: {duration: 20s}
      - setWeight: 50
      - pause: {duration: 20s}
      - setWeight: 60
      - pause: {duration: 20s}
      - setWeight: 70
      - pause: {duration: 20s}
      - setWeight: 80
      - pause: {duration: 20s}
      - setWeight: 90
      - pause: {duration: 20s}