image: 
  repository: test-app
  tag: "" # set in Chart
  pullPolicy: IfNotPresent

# deployment values
deployment:
  replicas: 1
  port: 8080
  portName: http
  protocol: TCP
  HTTPpath: /
  autoPromote: false
  scaleDownDelaySeconds: 30

# service values
service:
  protocol: TCP
  port: 80
  targetPort: 8080
  type: NodePort

# virtualService values
vsvc:
  hosts: [ "test-app.local" ]
  http:
    name: primary
    stableHost: test-app-stable
    stableWeight: 100
    canaryHost: test-app-canary
    canaryWeight: 0

# gateway values
gateway:
  istio: ingressgateway
  port: 8080
  portName: http
  protocol: HTTP
  hosts: ["*"]
